---
- name: Change LFN standard DNS servers on switching infrastructure

  hosts: LAB

  gather_facts: no

  tasks:

   - name: Configure standard LFN DNS servers on spoke site switches
     cisco.ios.ios_system:
      name_servers:
       - 10.10.10.2
       - 10.24.60.4
       - 10.25.60.4
     
   - name: Save running to startup if the playbook made a change
     cisco.ios.ios_config:
      save_when: changed