---
- name: Get IOS version

  hosts: LAB

  gather_facts: yes
  
#  vars_prompt:
#    - name: "ansible_user"
#      prompt: "Enter the username"
#      private: no
#    - name: "ansible_password"
#      prompt: "Enter the password"
#      private: yes

  tasks:
  
    - name: Get the IOS version
      debug:
        var: ansible_net_version
        
#    - name: Get the switch platform (9200, 2960 etc..)
#      debug:
#        var: "{{ ansible_facts['net_model'] }}"

#    - name: debug gather_facts
#      debug:
#        var: ansible_facts

    - name: Save output to local directory
      local_action:
        module: lineinfile
        dest: "../Playbook Outputs/IOS_version_inventory.txt"
        create: yes
        line: "Hostname:{{ inventory_hostname }} Platform:{{ ansible_facts['net_model'] }} IOS Version:{{ ansible_net_version }}\n"